project:
  type: website

website:
  title: Codelodex
  
  navbar:
    search: false
    right:
      - text: "Home"
        file: index.qmd
      - file: about.qmd
      - file: references.qmd
      
  sidebar:
    collapse-level: 1
    contents:
      - text: "Home"
        file: index.qmd
      - file: gettingstarted.qmd
      - section: "R"
        contents:
          - file: r_1_dmc.qmd
            text: "Home"
          - file: r_2_regex.qmd
      - section: "Stata"
        contents:
          - file: stata_1_dmc.qmd
      - section: "Supreme Court Database"
        contents:
          - file: scdb_1_prereq.qmd
          - file: scdb_2_r.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true