---
title: "References"
---

This site was created in R using Quarto, and open-source software supported by Posit. The theme and style of the website were come from Quarto's pre-existing themes using their publicly available code that can be found at [https://quarto.org](https://quarto.org).

The inspiration for this site was Vincent Arel-Bundock's wonderful documentation website for the `marginaleffects` package, which can be found at [https://marginaleffects.com](https://marginaleffects.com/). I have found Vincent's website extremely helpful, and hope my website can provide the a similar level of coding help. A citation to the `marginaleffects` package appears below.

> Arel-Bundock, Vincent, Noah Greifer, and Andrew Heiss. 2024. “How to Interpret Statistical Models Using marginaleffects for R and Python.” *Journal of Statistical Software* 111(9) 1-32. doi:10.18637/jss.v111.i09 [https://doi.org/10.18637/jss.v111.i09](https://doi.org/10.18637/jss.v111.i09).

Part of this site is dedicated to working with the Supreme Court Database (hereafter SCDB). I am in no way a part of the team of researchers that manages and updates the SCDB, but I am a frequent user of the database thanks to their dedicated effort to make the data accessible. A citation to the SCDB appears below. To give proper credit to the researchers in charge of the SCDB, I cite the SCDB on each an every page of code dedicated to working with the database. That citation appears below.

> Harold J. Spaeth, Lee Epstein, Michael J. Nelson, Andrew D. Martin, Jeffrey A. Segal, Theodore J. Ruger, and Sara C. Benesh. 2024. Supreme Court Database, Version 2024 Release 01. URL: [https://scdb.psu.edu](https://scdb.psu.edu)

If you hadn't picked it up already, I am a firm believer in citing sources. Throughout this site, I will draw upon many sources to help explain certain concepts, ideas, and procedures (e.g., calculating predictions from regression estimates). To help justify the methods I use, I will include an in-text citation to sources, and a full citation to the work at the bottom of the code page in which the citation appears. A full bibliography of the sources I cite appear below. 

> Arel-Bundock, Vincent, Noah Greifer, and Andrew Heiss. 2024. “How to Interpret Statistical Models Using marginaleffects for R and Python.” *Journal of Statistical Software* 111(9) 1-32. doi:10.18637/jss.v111.i09 [https://doi.org/10.18637/jss.v111.i09](https://doi.org/10.18637/jss.v111.i09).

> Bailey, Michael A. 2020. *Real Stats: Using Econometrics for Political Science and Public Policy*. 2nd Ed. Oxford University Press. 

> Box-Steffensmeier, Janet M. and Bradford S. Jones. 2004. *Event History Modeling A Guide for Social Scientists*. Cambridge University Press.

> Box-Steffensmeier, Janet M., John R. Freeman, Matthew P. Hitt, and Jon C. W. Pevehouse. 2014. *Time Series Analysis for the Social Sciences*. Cambridge University Press.

> Llaudet, Elena and Kosuke Imani. 2022. *Data Analysis for Social Science: A Friendly and Practical Introduction*. Princeton University Press.

> Gelman, Andrew and Jennifer Hill. 2007. *Data Analysis Using Regression and Multilevel/Hierarchical Models*. Cambridge University Press.

> Gelman, Andrew, Jennifer Hill, and Aki Vehtari. 2021. *Regression and Other Stories*. Cambridge University Press.

> Gill, Jeff. 2006. *Essential Mathematics for Political and Social Research*. Cambridge University Press.

> Imbens, Guido W. and Donald Rubin. 2015. *Causal Inference for Statistics, Social, and Biomedical Sciences An Introduction*. Cambridge University Press.

> Imai, Kosuke. 2018. *Quantitative Social Science: An Introduction*. Princeton University Press.

> Imai, Kosuke and Lori D. Bougher 2021. *Quantitative Social Science: An Introduction in Stata*. Princeton University Press.

> Imai, Kosuke and Nora Webb Williams. 2022. *Quantitative Social Science: An Introduction in tidyverse*. Princeton University Press.

> Ward, Michael D. and John S. Ahlquist. 2018. *Maximum Likelihood for Social Science Strategies for Analysis*. Cambridge University Press.
